### ISSUE TITLE
Allow creation of both function and package builds

### ISSUE THREAD

**Issue by fgmacedo** [micmurawski/poetry-plugin-lambda-build#30]
Hi, thanks for this plugin!

Context: I'm testing locally with `localstack` community, that don't allow the Layers feature. 

So, I'd like to generate package and function exports, the `package.zip` for local tests, and `function.zip` for the real upload pipeline.

My config is like this, but only `dist/layer.zip` and `dist/function.zip` are generated:

```toml
[tool.poetry-plugin-lambda-build]
layer-artifact-path = "dist/layer.zip"
layer-install-dir = ""
function-install-dir = ""
package-artifact-path = "dist/package.zip"
function-artifact-path = "dist/function.zip"
only="main"
```

Do you agree with this request?

If you agree, I will happily try to get a PR.  One possible approach is to turn [`BuildType`](https://github.com/micmurawski/poetry-plugin-lambda-build/blob/0bd3f9b47356dc564ad10824dc17a1de47d63ab5/poetry_plugin_lambda_build/recipes.py#L46) into [`Flag`](https://docs.python.org/3/library/enum.html#enum.Flag), so multiple options can be merged.

Something like this:

```python
import enum


class BuildType(enum.Flag):
    IN_CONTAINER = enum.auto()
    MERGED = enum.auto()
    SEPARATED = enum.auto()
```

My use case:

```python
BuildType.MERGED | BuildType.SEPARATED
```

The current options can still be obtained:
```python
BuildType.IN_CONTAINER | BuildType.MERGED
BuildType.IN_CONTAINER | BuildType.SEPARATED
```

What do you think about this approach?

Best regards!
