### ISSUE TITLE
Dependencies are missing in built zip

### ISSUE THREAD

**Issue by Levelleor** [micmurawski/poetry-plugin-lambda-build#43]
I've used the provided example:
```
[tool.poetry-plugin-lambda-build]
package-artifact-path = "package.zip"
```

But it seems like the zip that I get out of `poetry build-lambda` does not contain the dependencies of the project, only source code and some metadata files.

Is this expected behavior? I think lambda requires dependencies be on the same level as the source code, the provided zip then is invalid.

I am on Poetry 2.1.1, plugin 1.0.8. 

I also tried more verbose logging but it seems like there isn't really any additional info present even on the highest level.

**Comment by micmurawski** [comment]
@Levelleor Can you provide the exact shape of your pyproject.toml?

**Comment by Levelleor** [comment]
Hi @micmurawski , thank you for reaching out!

The entire pyproject is below, omitted some private parts like sources but all fields are present:
```toml
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["My name", "email@example.net"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.35.54"
poethepoet = "^0.33.0"
requests = "^2.32.3"

[[tool.poetry.source]]
name = "nexus"
url = "https://nexus.net/repo/repository/pypi/simple/"
priority = "primary"

[tool.poetry.group.dev.dependencies]
nox = "^2024.10.9"
poethepoet = "^0.33.0"
pytest = "^8.3.5"
nox-poetry = "^1.2.0"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"
poetry-plugin-lambda-build = ">=1.0.8"

# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
preinstall.shell = "python scripts/preinstall.py"
test.shell = "nox"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "packagezip"
```

This is not a package and this demo config is quite old, considering there's an update to setting dependencies compatible with PEP standards, described here: https://python-poetry.org/docs/dependency-specification/

Though, seems like poetry.dependencies is still valid and should work. Any clues what's happening based off the config?
